import type { Combo, Destination } from "@/lib/types";

export const FALLBACK_DESTINATIONS: Destination[] = [
  {
    id: 1,
    name: "Málaga",
    slug: "malaga",
    region: "Costa del Sol",
    country: "España",
    blurb: "Playa urbana, tapeo y barrios para perderse sin apuro.",
    cover_url: "/covers/malaga.jpg",
    description:
      "Málaga no es solo el aeropuerto de la Costa del Sol. Es alcazaba al atardecer, playa urbana, museos que no aburren y un casco antiguo para caminar con un helado.\n\nIdeal para una primera vez en Andalucía o para volver y verla con otra onda: Soho, El Palo, Pedregalejo y un ritmo que no copia el top 10.",
    published: true,
    featured: true,
    created_at: "2026-01-01",
  },
  {
    id: 2,
    name: "Nerja",
    slug: "nerja",
    region: "Costa Tropical",
    country: "España",
    blurb: "Balcón de Europa, calas y pueblo frente al mar.",
    cover_url: "/covers/nerja.jpg",
    description:
      "Nerja es villa de postal: Balcón de Europa, casco blanco y calas. Queda a una hora de Málaga. Se arma lindo como escapada o como parte de un combo más largo por la costa.",
    published: true,
    featured: true,
    created_at: "2026-01-01",
  },
  {
    id: 3,
    name: "Andalucía",
    slug: "andalucia",
    region: "Pueblos blancos y Caminito",
    country: "España",
    blurb: "Pueblos blancos, miradores y el Caminito del Rey.",
    cover_url: "/covers/andalucia.jpg",
    description:
      "Andalucía se siente distinto cuando salís de la costa un rato: callejones, miradores, brunch de tapas y el Caminito del Rey con la logística resuelta.",
    published: true,
    featured: true,
    created_at: "2026-01-01",
  },
  {
    id: 4,
    name: "Lisboa",
    slug: "lisboa",
    region: "Estuario del Tajo",
    country: "Portugal",
    blurb: "Miradores, tranvía y un ritmo para no terminar hecha bolsa.",
    cover_url: "/covers/lisboa.jpg",
    description:
      "Lisboa se disfruta despacio: subidas, luces y un atardecer que pide vino, no checklist. Un barrio para volver a dormir y dos o tres anclas por día.",
    published: true,
    featured: true,
    created_at: "2026-01-01",
  },
  {
    id: 5,
    name: "Puglia",
    slug: "puglia",
    region: "El sur que pega",
    country: "Italia",
    blurb: "Pueblos blancos, mar adriático y comida de verdad.",
    cover_url: "/covers/puglia.jpg",
    description:
      "Puglia es mar, trulli y pueblos para perderse. Ostuni, Polignano, Lecce: el sur de Italia sin el circo del norte.",
    published: true,
    featured: true,
    created_at: "2026-01-01",
  },
  {
    id: 6,
    name: "Marrakech",
    slug: "marrakech",
    region: "Medina y Atlas",
    country: "Marruecos",
    blurb: "Riads, zocos y un día en las montañas.",
    cover_url: "/covers/marrakech.jpg",
    description:
      "Marrakech pide un riad lindo y un plan para no marearte en la medina. Después, Atlas o Essaouira.",
    published: true,
    featured: true,
    created_at: "2026-01-01",
  },
];

export const FALLBACK_COMBOS: Combo[] = [
  {
    id: 1,
    title: "Málaga con style",
    slug: "malaga-con-style",
    destination: "Málaga, España",
    duration: "4 días",
    price_from: 390,
    currency: "EUR",
    excerpt: "Playa, tapeo, arte y barrios para perderse sin apuro.",
    cover_url: "/covers/malaga.jpg",
    published: true,
    featured: true,
    created_at: "2026-01-01",
    places: ["malaga"],
    itinerary: [
      "Día 1 — Llegada, check-in y tapeo en el centro (sin Larios a las 14 hs)",
      "Día 2 — Alcazaba, casco y atardecer en La Malagueta",
      "Día 3 — Barrio (Soho o El Palo) y playa urbana",
      "Día 4 — Mañana libre o pueblo cercano y vuelo",
    ],
    destinations: [{ id: 1, name: "Málaga", slug: "malaga", cover_url: "/covers/malaga.jpg", region: "Costa del Sol", country: "España" }],
  },
  {
    id: 2,
    title: "Andalucía real: pueblos + Caminito",
    slug: "andalucia-real-pueblos-caminito",
    destination: "Málaga y pueblos blancos",
    duration: "6 días",
    price_from: 680,
    currency: "EUR",
    excerpt: "Caminito del Rey, un pueblo blanco y Málaga.",
    cover_url: "/covers/andalucia.jpg",
    published: true,
    featured: true,
    created_at: "2026-01-01",
    places: ["malaga", "andalucia"],
    itinerary: [
      "Día 1 — Málaga: aterrizaje, barrio y primera noche de tapeo",
      "Día 2 — Casco, Alcazaba y ritmo de ciudad",
      "Día 3 — Pueblo blanco (callejones, mirador, brunch)",
      "Día 4 — Caminito del Rey: entradas, traslado y plan B por clima",
      "Día 5 — Playa o El Palo, sin checklist",
      "Día 6 — Cierre en Málaga y vuelo",
    ],
    destinations: [
      { id: 1, name: "Málaga", slug: "malaga", cover_url: "/covers/malaga.jpg", region: "Costa del Sol", country: "España" },
      { id: 3, name: "Andalucía", slug: "andalucia", cover_url: "/covers/andalucia.jpg", region: "Pueblos blancos y Caminito", country: "España" },
    ],
  },
  {
    id: 3,
    title: "Nerja y Costa Tropical",
    slug: "nerja-y-costa-tropical",
    destination: "Nerja, Málaga",
    duration: "3 días",
    price_from: 320,
    currency: "EUR",
    excerpt: "Balcón de Europa, calas y pueblo: la escapada de playa desde Málaga.",
    cover_url: "/covers/nerja.jpg",
    published: true,
    featured: true,
    created_at: "2026-01-01",
    places: ["nerja", "malaga"],
    itinerary: [
      "Día 1 — Málaga de mañana, bus a Nerja, casco y Balcón de Europa",
      "Día 2 — Cala o Cuevas, pueblo al atardecer",
      "Día 3 — Último baño y vuelta a Málaga",
    ],
    destinations: [
      { id: 2, name: "Nerja", slug: "nerja", cover_url: "/covers/nerja.jpg", region: "Costa Tropical", country: "España" },
      { id: 1, name: "Málaga", slug: "malaga", cover_url: "/covers/malaga.jpg", region: "Costa del Sol", country: "España" },
    ],
  },
  {
    id: 4,
    title: "Lisboa con calma",
    slug: "lisboa-con-calma",
    destination: "Lisboa, Portugal",
    duration: "5 días",
    price_from: 520,
    currency: "EUR",
    excerpt: "Miradores, tranvía y un ritmo para caminar la ciudad sin terminar hecha bolsa.",
    cover_url: "/covers/lisboa.jpg",
    published: true,
    featured: true,
    created_at: "2026-01-01",
    places: ["lisboa"],
    itinerary: [
      "Día 1 — Barrio (Alfama o Graça), mirador y cena sin prisa",
      "Día 2 — Centro, tranvía y un atardecer con vino",
      "Día 3 — Príncipe Real / Chiado",
      "Día 4 — Sintra o Cascais, según el clima",
      "Día 5 — Mañana lenta y vuelo",
    ],
    destinations: [{ id: 4, name: "Lisboa", slug: "lisboa", cover_url: "/covers/lisboa.jpg", region: "Estuario del Tajo", country: "Portugal" }],
  },
  {
    id: 5,
    title: "Puglia, el sur que pega",
    slug: "puglia-el-sur-que-pega",
    destination: "Puglia, Italia",
    duration: "7 días",
    price_from: 890,
    currency: "EUR",
    excerpt: "Pueblos blancos, mar adriático y comida de verdad.",
    cover_url: "/covers/puglia.jpg",
    published: true,
    featured: true,
    created_at: "2026-01-01",
    places: ["puglia"],
    itinerary: [
      "Día 1 — Llegada y base (no hotel distinto cada noche)",
      "Día 2 — Pueblo blanco y mar",
      "Día 3 — Polignano o costa",
      "Día 4 — Lecce y comida de verdad",
      "Día 5 — Playa / masseria",
      "Día 6 — Un pueblo extra sin matar el auto",
      "Día 7 — Cierre y salida",
    ],
    destinations: [{ id: 5, name: "Puglia", slug: "puglia", cover_url: "/covers/puglia.jpg", region: "El sur que pega", country: "Italia" }],
  },
  {
    id: 6,
    title: "Marrakech y el Atlas",
    slug: "marrakech-y-el-atlas",
    destination: "Marrakech, Marruecos",
    duration: "6 días",
    price_from: 640,
    currency: "EUR",
    excerpt: "Medina, riads y un día en las montañas.",
    cover_url: "/covers/marrakech.jpg",
    published: true,
    featured: true,
    created_at: "2026-01-01",
    places: ["marrakech"],
    itinerary: [
      "Día 1 — Riad en la medina, rooftop y primer zoco con mapa",
      "Día 2 — Medina con ritmo",
      "Día 3 — Jardines y terraza",
      "Día 4 — Atlas o Essaouira",
      "Día 5 — Vuelta a la ciudad",
      "Día 6 — Mañana lenta y salida",
    ],
    destinations: [{ id: 6, name: "Marrakech", slug: "marrakech", cover_url: "/covers/marrakech.jpg", region: "Medina y Atlas", country: "Marruecos" }],
  },
];

export function listed<T>(value: T[] | undefined | null, fallback: T[]) {
  return value && value.length > 0 ? value : fallback;
}

export function destinationBySlug(slug: string) {
  return FALLBACK_DESTINATIONS.find((place) => place.slug === slug);
}

export function comboBySlug(slug: string) {
  return FALLBACK_COMBOS.find((combo) => combo.slug === slug);
}
